server:
  port: 8081
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  packages-to-scan: com.someverything.howWear.controller
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath*:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa